name: Qodana

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  qodana-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Qodana Scan for PR'
        uses: JetBrains/qodana-action@v2023.2.8
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}

  qodana-push-or-manual:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.2.8
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
        with:
          push-fixes: pull-request
